"""Automatic project documentation helpers for autonomous runs."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class DocumentationResult:
    """Summary of documentation generated for one workspace."""

    readme_path: str | None = None
    architecture_path: str | None = None
    annotated_files: list[str] | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "readme_path": self.readme_path,
            "architecture_path": self.architecture_path,
            "annotated_files": list(self.annotated_files or []),
        }


class DocGenerator:
    """Generate lightweight project docs from workflow context."""

    COMMENT_PREFIXES = {
        ".py": "#",
        ".sh": "#",
        ".yml": "#",
        ".yaml": "#",
        ".toml": "#",
        ".ini": "#",
        ".js": "//",
        ".cjs": "//",
        ".mjs": "//",
        ".ts": "//",
        ".tsx": "//",
        ".jsx": "//",
        ".java": "//",
        ".kt": "//",
        ".rs": "//",
        ".go": "//",
        ".css": "/*",
    }

    def generate(
        self,
        *,
        workspace_root: Path,
        blueprint: Any,
        executions: list[dict[str, Any]],
        trace_snapshot: dict[str, Any],
        touched_files: list[str] | None = None,
        managed_workspace: bool = True,
    ) -> DocumentationResult:
        workspace_root = Path(workspace_root).expanduser().resolve()
        workspace_root.mkdir(parents=True, exist_ok=True)

        readme_path = workspace_root / "README.md"
        architecture_path = workspace_root / "ARCHITECTURE.md"

        readme_path.write_text(
            self._build_readme(
                workspace_root=workspace_root,
                blueprint=blueprint,
                executions=executions,
                trace_snapshot=trace_snapshot,
            ),
            encoding="utf-8",
        )
        architecture_path.write_text(
            self._build_architecture(
                workspace_root=workspace_root,
                blueprint=blueprint,
                executions=executions,
                trace_snapshot=trace_snapshot,
            ),
            encoding="utf-8",
        )

        annotated_files: list[str] = []
        if managed_workspace:
            for path in self._candidate_files(workspace_root, touched_files or []):
                if self._annotate_file(path, blueprint.goal):
                    annotated_files.append(str(path))

        return DocumentationResult(
            readme_path=str(readme_path),
            architecture_path=str(architecture_path),
            annotated_files=annotated_files,
        )

    def _build_readme(
        self,
        *,
        workspace_root: Path,
        blueprint: Any,
        executions: list[dict[str, Any]],
        trace_snapshot: dict[str, Any],
    ) -> str:
        scripts = self._detect_scripts(workspace_root)
        status = trace_snapshot.get("status") or "completed"
        task_lines = "\n".join(
            f"- `{task.id}`: {task.task_type} via `{task.agent or 'unassigned'}`"
            for task in blueprint.tasks
        )
        run_lines = "\n".join(f"- `{script}`" for script in scripts) if scripts else "- Inspect the generated source files directly."
        return (
            f"# {workspace_root.name}\n\n"
            f"Generated by NEXUS for the goal:\n\n"
            f"> {blueprint.goal}\n\n"
            f"## Status\n\n"
            f"- Workflow status: `{status}`\n"
            f"- Tasks executed: `{len(executions)}`\n"
            f"- Primary intent: `{blueprint.primary_intent}`\n\n"
            f"## Plan\n\n"
            f"{task_lines}\n\n"
            f"## How To Run\n\n"
            f"{run_lines}\n\n"
            f"## Notes\n\n"
            f"- `ARCHITECTURE.md` captures the workflow decisions and touched files.\n"
            f"- Generated in `{workspace_root}`.\n"
        )

    def _build_architecture(
        self,
        *,
        workspace_root: Path,
        blueprint: Any,
        executions: list[dict[str, Any]],
        trace_snapshot: dict[str, Any],
    ) -> str:
        decision_rows = [
            {
                "type": row.get("decision_type"),
                "task_id": row.get("task_id"),
                "reason": row.get("reason"),
            }
            for row in (trace_snapshot.get("decisions") or [])[:24]
        ]
        execution_rows = "\n".join(
            f"- `{item['task_id']}`: `{item['status']}` after {item['attempts']} attempt(s)"
            for item in executions
        ) or "- No task executions recorded."
        decisions_json = json.dumps(decision_rows, indent=2)
        return (
            f"# Architecture\n\n"
            f"## Goal\n\n"
            f"{blueprint.goal}\n\n"
            f"## Workflow\n\n"
            f"{execution_rows}\n\n"
            f"## Constraints\n\n"
            + ("\n".join(f"- `{constraint}`" for constraint in blueprint.metadata.get("constraints", [])) or "- None recorded.")
            + "\n\n"
            f"## Runtime Decisions\n\n"
            f"```json\n{decisions_json}\n```\n\n"
            f"## Workspace\n\n"
            f"- Root: `{workspace_root}`\n"
            f"- Trace: `{trace_snapshot.get('trace_path', '--')}`\n"
        )

    def _detect_scripts(self, workspace_root: Path) -> list[str]:
        scripts: list[str] = []
        package_json = workspace_root / "package.json"
        if package_json.exists():
            try:
                payload = json.loads(package_json.read_text(encoding="utf-8"))
                for name in ("dev", "start", "build", "test"):
                    if name in payload.get("scripts", {}):
                        scripts.append(f"npm run {name}")
            except json.JSONDecodeError:
                pass
        if (workspace_root / "pyproject.toml").exists():
            scripts.append("python -m pytest")
        else:
            top_level_tests = list(workspace_root.glob("test_*.py"))
            tests_dir = workspace_root / "tests"
            nested_tests = list(tests_dir.glob("test_*.py")) if tests_dir.exists() else []
            if top_level_tests or nested_tests:
                scripts.append("python -m unittest discover -s tests -p \"test_*.py\"")
        return scripts

    def _candidate_files(self, workspace_root: Path, touched_files: list[str]) -> list[Path]:
        candidates: list[Path] = []
        for raw in touched_files[:12]:
            raw_path = Path(raw)
            if raw_path.is_absolute():
                try:
                    path = raw_path.resolve().relative_to(workspace_root)
                except ValueError:
                    continue
                path = workspace_root / path
            else:
                path = workspace_root / raw_path
            if path.is_file() and path.suffix in self.COMMENT_PREFIXES:
                candidates.append(path)
        return candidates

    def _annotate_file(self, path: Path, goal: str) -> bool:
        try:
            original = path.read_text(encoding="utf-8")
        except Exception:
            return False
        if not original.strip():
            return False

        prefix = self.COMMENT_PREFIXES.get(path.suffix)
        if not prefix:
            return False

        if prefix == "/*":
            comment = f"/* NEXUS note: {path.name} supports the workflow goal: {goal}. */\n"
            if original.lstrip().startswith("/* NEXUS note:"):
                return False
        else:
            comment = f"{prefix} NEXUS note: {path.name} supports the workflow goal: {goal}.\n"
            if original.lstrip().startswith(f"{prefix} NEXUS note:"):
                return False

        path.write_text(comment + original, encoding="utf-8")
        return True
